from app.document_types.spec import LITERAL, DocumentTypeSpec, FieldSpec

SPEC = DocumentTypeSpec(
    slug="psa",
    name="Professional Services Agreement",
    description=(
        "A framework agreement for engaging a services provider under one or more "
        "statements of work, covering deliverables, intellectual property, payment, "
        "warranties, and liability."
    ),
    filename="psa.md",
    party_roles=("Provider", "Customer"),
    fields=(
        FieldSpec("effective_date", "Effective Date", "date"),
        FieldSpec("governing_law", "Governing Law", "text"),
        FieldSpec("chosen_courts", "Chosen Courts", "text"),
        FieldSpec("general_cap_amount", "General Cap Amount", "text", required=False),
        FieldSpec("increased_cap_amount", "Increased Cap Amount", "text", required=False),
        FieldSpec("increased_claims", "Increased Claims", "multiline", required=False),
        FieldSpec("unlimited_claims", "Unlimited Claims", "multiline", required=False),
        FieldSpec("additional_warranties", "Additional Warranties", "multiline", required=False),
        FieldSpec("provider_covered_claims", "Provider Covered Claims", "multiline", required=False),
        FieldSpec("customer_covered_claims", "Customer Covered Claims", "multiline", required=False),
        FieldSpec("customer_policies", "Customer Policies", "multiline", required=False),
        FieldSpec("insurance_minimums", "Insurance Minimums", "multiline", required=False),
        FieldSpec("security_policy", "Security Policy", "multiline", required=False),
        FieldSpec("dpa_reference", "DPA Reference", "text", required=False),
        FieldSpec(
            "statement_of_work_details",
            "Statement of Work Details (deliverables, fees, payment period, timelines, etc.)",
            "multiline",
            required=False,
        ),
    ),
    clause_mapping={
        "Customer": LITERAL,
        "Customer's": LITERAL,
        "Provider": LITERAL,
        "Provider's": LITERAL,
        "Additional Warranties": "additional_warranties",
        "Chosen Courts": "chosen_courts",
        "Customer Covered Claim": "customer_covered_claims",
        "Customer Covered Claims": "customer_covered_claims",
        "Customer Policies": "customer_policies",
        "DPA": "dpa_reference",
        "Effective Date": "effective_date",
        "General Cap Amount": "general_cap_amount",
        "Governing Law": "governing_law",
        "Increased Cap Amount": "increased_cap_amount",
        "Increased Claims": "increased_claims",
        "Insurance Minimums": "insurance_minimums",
        "Provider Covered Claim": "provider_covered_claims",
        "Provider Covered Claims": "provider_covered_claims",
        "SOW Term": LITERAL,
        "Security Policy": "security_policy",
        "Unlimited Claims": "unlimited_claims",
        "Customer Obligations": LITERAL,
        "Deliverable": LITERAL,
        "Deliverables": LITERAL,
        "Fees": LITERAL,
        "Payment Period": LITERAL,
        "Rejection Period": LITERAL,
        "Resubmission Period": LITERAL,
        "Time of Assignment": LITERAL,
    },
)
